name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files in working directory
        run: ls -la

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover

      - name: Build Docker image
        run: docker build -t devsecops-lab .

      - name: Run SonarCloud Analysis
        run: |
          docker run --rm \
          -e SONAR_HOST_URL="https://sonarcloud.io" \
          -e SONAR_LOGIN=${{ secrets.SONAR_TOKEN }} \
          -v "$(pwd):/usr/src" \
          sonarsource/sonar-scanner-cli